Repository decentraland/explorer-website, pull requests merged in 2023-01, with the labels that each got.

#327 fix: download modal always shows
  src/__snapshots__/storybook.test.ts.snap
  src/integration/desktop.ts
Labels: bug

#333 fix: reduce clutter
  package.json
  public/images/background-v3@1x.jpg
  public/images/background-v3@2x.jpg
  public/images/background-v3@3x.jpg
  public/images/background-v3@4x.jpg
  public/images/loading.gif
  public/index.html
  src/@types/static.d.ts
  src/__snapshots__/storybook.test.ts.snap
  src/components/App.tsx
  src/components/common/Audio.stories.tsx
  src/components/common/Loading/LoadingRender.css
  src/components/common/Loading/LoadingRender.stories.tsx
  src/components/common/Loading/LoadingRender.tsx
  src/components/errors/ErrorContainer.stories.tsx
  src/images/loading.mp4
Labels: stream-discoverability

#328 Update setupProxy.js
  src/setupProxy.js
Labels: stream-discoverability

#337 feat: show download screen if already signed in
  src/components/App.tsx
  src/state/selectors.ts
Labels: stream-core
